### ISSUE TITLE
Jupyter-git KF 1.8.0 image: module 'asyncio' has no attribute 'coroutine'

### ISSUE THREAD

**Issue by yingding** [kubeflow/manifests#2570]
While using the Jupyter notebook git with `kubeflownotebookswg/jupyter-scipy:v1.8.0` image.
I got Python 3.11+: module 'asyncio' has no attribute 'coroutine'.

It seems to be a know issue https://github.com/jupyterlab/jupyterlab-git/issues/1261#issuecomment-1688502127

**Comment by yingding** [comment]
The workaround is run the following cmd in your notebook cell. Stop and restart the notebook instance. 
```
import sys 
!{sys.executable} -m pip install --upgrade --user jupyterlab==4.0.8
!{sys.executable} -m pip install --upgrade --user pip install --pre "jupyterlab-git==0.50.0rc0"
!{sys.executable} -m pip install --upgrade --user pip install git+https://github.com/pexpect/pexpect.git@master
```
It is mentioned in https://github.com/jupyterlab/jupyterlab-git/issues/1245#issuecomment-1798057095, and https://github.com/pexpect/pexpect/issues/779, the pexpect lib will be cut soon. 
I am not sure if it also works with jupyterlab==3.6.6 and jupyterlab-git==0.44.0 directly with the next pexpect

**Comment by juliusvonkohout** [comment]
/close

@yingding please report this in kubeflow/kubeflow
